import { LandingPageConfig, LandingHeroSlide, LandingOffer, StockItem } from '../types';

export const DEFAULT_HERO_SLIDES: LandingHeroSlide[] = [
  {
    id: 'slide-1',
    tag: 'SHRI SAI ELECTRONICS EXPO • MEGA FESTIVAL SALE',
    titleLead: 'Smart 4K UHD TVs &',
    titleHighlight: 'Royal Teak Sofas',
    subtitle: 'Wardha’s Largest Showroom for Premium Electronics & Handmade Teakwood Furniture. Genuine Sony, Samsung, LG 4K Smart TVs and factory-direct furniture with 0% EMI.',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=1600&auto=format&fit=crop&q=80',
    primaryBtnText: 'Explore Wholesale Catalog',
    primaryBtnTarget: 'catalog',
    secondaryBtnText: '30-Month Scheme Passbook',
    secondaryBtnTarget: 'passbook',
    cardBadge: 'Mega Festive Deals',
    cardMetric: '100% Brand Warranty',
    cardMetric2: '0% Interest Easy EMI',
    themeColor: 'amber',
    active: true,
  },
  {
    id: 'slide-2',
    tag: '30-MONTH SAVINGS SCHEME • WEEKLY ₹100 / ₹200',
    titleLead: 'Monthly Lucky Draw & Guaranteed',
    titleHighlight: 'Home Appliances & Furniture',
    subtitle: 'Save just ₹100 or ₹200 every week! Transparent monthly lucky draw — win your chosen product immediately with all remaining installments 100% waived off!',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1600&auto=format&fit=crop&q=80',
    primaryBtnText: 'Check Scheme Passbook',
    primaryBtnTarget: 'passbook',
    secondaryBtnText: 'Open New Card via WhatsApp',
    secondaryBtnTarget: 'whatsapp',
    cardBadge: '#1 Savings Scheme',
    cardMetric: 'Starting at ₹100/Week',
    cardMetric2: 'Monthly Lucky Draw Gifts',
    themeColor: 'purple',
    active: true,
  },
  {
    id: 'slide-3',
    tag: 'PURE TEAKWOOD CRAFTSMANSHIP • DIRECT FACTORY RATES',
    titleLead: 'Solid Teak Sofas, Diwans &',
    titleHighlight: 'Heavy Steel Almirahs',
    subtitle: 'Crafted from 100% genuine seasoned Chandrapur teakwood without middlemen. Lifetime wood durability guarantee and free home delivery across Wardha district.',
    imageUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef0?w=1600&auto=format&fit=crop&q=80',
    primaryBtnText: 'View Furniture Collection',
    primaryBtnTarget: 'catalog',
    secondaryBtnText: 'Contact Showroom on WhatsApp',
    secondaryBtnTarget: 'whatsapp',
    cardBadge: 'Direct Factory Price',
    cardMetric: 'Wholesale Direct Rates',
    cardMetric2: 'Lifetime Wood Guarantee',
    themeColor: 'emerald',
    active: true,
  },
];

export const DEFAULT_OFFERS: LandingOffer[] = [
  {
    id: 'off-1',
    title: 'Up to 50% Off on Smart 4K UHD TVs',
    subtitle: 'Mega festival discount on Samsung, Sony & LG 32" to 65" 4K Smart TVs with free wall-mount installation.',
    badge: 'MEGA DEAL',
    discount: 'Up to 50% OFF',
    couponCode: 'SAI4KTV',
    validTill: 'Limited Time Offer',
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&auto=format&fit=crop&q=80',
    whatsappMessage: 'Hello, I want to inquire about the Up to 50% Off Smart 4K TV offer.',
    active: true,
  },
  {
    id: 'off-2',
    title: 'Free Center Table with Teak Sofa Sets',
    subtitle: 'Get a ₹4,500 designer glass-top center table completely FREE on purchase of any 3+1+1 or 3+2 Teakwood Sofa Set!',
    badge: 'FREE GIFT',
    discount: '₹4,500 Table FREE',
    couponCode: 'FREETABLE',
    validTill: 'Valid Till Month End',
    category: 'Furniture',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80',
    whatsappMessage: 'Hello, I am interested in the Teakwood Sofa Set with Free Center Table offer.',
    active: true,
  },
  {
    id: 'off-3',
    title: '30-Month Weekly Scheme - ₹500 Shopping Voucher',
    subtitle: 'Enroll in our 30-Month Weekly Savings Card today and receive a free digital passbook and ₹500 shopping voucher.',
    badge: 'LUCKY DRAW',
    discount: '₹500 Voucher Free',
    couponCode: 'LUCKY30',
    validTill: 'For New Members',
    category: 'Scheme',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop&q=80',
    whatsappMessage: 'Hello, I want to open a new card for the 30-Month Weekly Savings Scheme.',
    active: true,
  },
  {
    id: 'off-4',
    title: 'Old For New - Mega Exchange Festival',
    subtitle: 'Exchange any old TV, refrigerator, cooler or sofa set and get up to ₹8,000 instant bonus exchange credit.',
    badge: 'EXCHANGE BONUS',
    discount: 'Up to ₹8,000 Extra',
    couponCode: 'EXCHANGE2026',
    validTill: 'Active This Month',
    category: 'Appliances',
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
    whatsappMessage: 'Hello, I would like to exchange my old home appliances/furniture for new items.',
    active: true,
  },
];

export const DEFAULT_LANDING_CONFIG: LandingPageConfig = {
  announcement: {
    enabled: true,
    badge: '🌟 Special Festive Sale',
    text: 'Shri Sai Enterprises Wardha • Mega Showroom Expo is Live! Up to 50% Off, 0% Interest EMI & Free District Delivery!',
    highlightText: 'Contact Showroom Directly',
    whatsappButtonText: 'WhatsApp Inquiry',
  },
  heroSlides: DEFAULT_HERO_SLIDES,
  offers: DEFAULT_OFFERS,
  contactInfo: {
    helpline1: '8766486915',
    helpline2: '8600122978',
    helpline3: '9175537365',
    whatsappNumber: '918766486915',
    addressHindi: 'Opp. Matoshree Sabhagruh, Arvi Road, Punjab Colony, Wardha - 442001',
    landmark: 'Near Shivaji Chowk, Arvi Road',
    googleMapLink: 'https://share.google/pRPd28v4DoL3a5Ocr',
    timings: 'Open Daily: 9:30 AM – 9:30 PM (All 7 Days)',
  },
  schemeBanner: {
    title: 'Buy Premium Furniture & Electronics on Wardha’s #1 30-Month Weekly Savings Scheme!',
    subtitle: 'Save just ₹100 or ₹200 weekly! Enjoy transparent monthly lucky draws — if your card number is picked, you win your selected appliance or furniture immediately with zero remaining installments! After 30 months, all participants receive their full savings plus a ₹500 bonus.',
    badge: '30-MONTH WEEKLY SAVINGS & MONTHLY LUCKY DRAW SCHEME • WARDHA’S #1 TRUSTED SCHEME',
    weeklyBadge1: 'Weekly Installment: Just ₹100 or ₹200/Week',
    weeklyBadge2: 'Monthly Lucky Draw Bumper Gifts',
    highlightNote: '100% Safe & Guaranteed Delivery',
  },
  enableOffersSection: true,
  enableAnnouncementBar: true,
  showHeroSection: true,
  showSchemeBanner: true,
  showReviewsSection: true,
  showElectronicsSection: true,
  showFurnitureSection: true,
  showAddressBanner: true,
  showPassbookSection: true,
};

export const SAMPLE_SHOWROOM_PRODUCTS: Omit<StockItem, 'id' | 'updatedAt'>[] = [
  {
    code: 'TV-SAM-55-UHD',
    name: 'Samsung 55-inch Crystal 4K UHD Smart TV (AUE60A)',
    category: 'Electronics',
    brand: 'Samsung',
    model: 'UA55AUE60AKXXL',
    purchasePrice: 38000,
    salePrice: 44990,
    mrp: 64900,
    stockQty: 8,
    minAlertQty: 2,
    unit: 'Units',
    warrantyMonths: 24,
    description: '4K Ultra HD Display with PurColor, HDR10+, Smart Hub, 20W Dolby Audio, and AirPlay 2.',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: 'Festive 31% Off',
    schemeWeeklyAmount: 200,
    hideOnLanding: false,
  },
  {
    code: 'TV-LG-43-SMART',
    name: 'LG 43-inch 4K WebOS Smart LED Television',
    category: 'Electronics',
    brand: 'LG',
    model: '43UQ7500PSF',
    purchasePrice: 24500,
    salePrice: 28990,
    mrp: 41990,
    stockQty: 12,
    minAlertQty: 3,
    unit: 'Units',
    warrantyMonths: 24,
    description: 'α5 Gen5 AI Processor 4K, ThinQ AI, Magic Remote Support, and 4K Active HDR.',
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: 'Best Seller',
    schemeWeeklyAmount: 150,
    hideOnLanding: false,
  },
  {
    code: 'FURN-SOFA-TEAK-311',
    name: 'Royal Pure Teakwood 3+1+1 Sofa Set with Cushions',
    category: 'Furniture',
    brand: 'Sai Craft',
    model: 'SC-SOFA-ROYAL-TK',
    purchasePrice: 28000,
    salePrice: 35900,
    mrp: 48000,
    stockQty: 5,
    minAlertQty: 1,
    unit: 'Sets',
    warrantyMonths: 60,
    description: '100% Genuine seasoned Chandrapur teakwood frame, 32-density high-resilience foam, with washable velvet fabric.',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: 'Direct Factory Rate',
    schemeWeeklyAmount: 200,
    hideOnLanding: false,
  },
  {
    code: 'FURN-DIWAN-STORAGE-4X6',
    name: 'Wooden Box Storage Diwan Cot (4x6 Feet) with Hydraulic Lift',
    category: 'Furniture',
    brand: 'Sai Craft',
    model: 'SC-DIWAN-BOX-46',
    purchasePrice: 11000,
    salePrice: 14500,
    mrp: 19500,
    stockQty: 7,
    minAlertQty: 2,
    unit: 'Pcs',
    warrantyMonths: 36,
    description: 'Solid heavy commercial ply & teak border structure with spacious hydraulic storage for blankets and mattresses.',
    imageUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef0?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: 'Hot Deal',
    schemeWeeklyAmount: 100,
    hideOnLanding: false,
  },
  {
    code: 'APPL-FRIDGE-LG-240L',
    name: 'LG 240L Smart Inverter Double Door Refrigerator (Shiny Steel)',
    category: 'Home Appliances',
    brand: 'LG',
    model: 'GL-S292RDSX',
    purchasePrice: 22000,
    salePrice: 26490,
    mrp: 34990,
    stockQty: 6,
    minAlertQty: 2,
    unit: 'Units',
    warrantyMonths: 120,
    description: 'Smart Inverter Compressor, Multi Air Flow Cooling, Toughened Glass Shelves, 10-Year Compressor Warranty.',
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: '5-Star Energy Saver',
    schemeWeeklyAmount: 150,
    hideOnLanding: false,
  },
  {
    code: 'FURN-ALMIRAH-STEEL-TRIPLE',
    name: 'Heavy Steel 3-Door Wardrobe Almirah with Locker & Mirror',
    category: 'Furniture',
    brand: 'Steel Craft',
    model: 'SC-ALM-STEEL-3D',
    purchasePrice: 12500,
    salePrice: 16500,
    mrp: 22000,
    stockQty: 9,
    minAlertQty: 2,
    unit: 'Units',
    warrantyMonths: 36,
    description: 'Heavy 18-gauge cold-rolled steel, powder-coated finish, ultra-secure locker box, and full-length dressing mirror.',
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: 'Heavy Duty Steel',
    schemeWeeklyAmount: 100,
    hideOnLanding: false,
  },
  {
    code: 'APPL-WASH-WHIRL-75KG',
    name: 'Whirlpool 7.5 Kg 5 Star Fully Automatic Top Load Washing Machine',
    category: 'Home Appliances',
    brand: 'Whirlpool',
    model: 'WHIRL-ROYAL-75',
    purchasePrice: 13500,
    salePrice: 16990,
    mrp: 22500,
    stockQty: 5,
    minAlertQty: 1,
    unit: 'Units',
    warrantyMonths: 24,
    description: '6th Sense Technology, Spiro Wash Action, Express Wash, Zero Pressure Fill, Hard Water Wash Support.',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: false,
    landingBadge: '0% Downpayment',
    schemeWeeklyAmount: 100,
    hideOnLanding: false,
  },
  {
    code: 'APPL-COOLER-SYMPHONY-70L',
    name: 'Heavy Duty 70-Litre Desert Air Cooler with Honeycomb Pads',
    category: 'Home Appliances',
    brand: 'Symphony',
    model: 'DESERT-STORM-70',
    purchasePrice: 8200,
    salePrice: 10990,
    mrp: 14990,
    stockQty: 10,
    minAlertQty: 2,
    unit: 'Units',
    warrantyMonths: 12,
    description: 'High air delivery powerful blower, 3-sided dense honeycomb cooling pads, inverter compatible with castor wheels.',
    imageUrl: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: false,
    landingBadge: 'Summer Special',
    schemeWeeklyAmount: 100,
    hideOnLanding: false,
  },
];

export function getActiveLandingConfig(config?: LandingPageConfig): LandingPageConfig {
  if (!config) {
    return DEFAULT_LANDING_CONFIG;
  }
  return {
    announcement: {
      ...DEFAULT_LANDING_CONFIG.announcement,
      ...(config.announcement || {}),
    },
    heroSlides: config.heroSlides && config.heroSlides.length > 0 ? config.heroSlides : DEFAULT_HERO_SLIDES,
    offers: config.offers && config.offers.length > 0 ? config.offers : DEFAULT_OFFERS,
    contactInfo: {
      ...DEFAULT_LANDING_CONFIG.contactInfo,
      ...(config.contactInfo || {}),
      helpline1: (config.contactInfo?.helpline1 === '9422114247' || !config.contactInfo?.helpline1)
        ? '8766486915'
        : config.contactInfo.helpline1,
    },
    schemeBanner: {
      ...DEFAULT_LANDING_CONFIG.schemeBanner,
      ...(config.schemeBanner || {}),
    },
    enableOffersSection: config.enableOffersSection !== false,
    enableAnnouncementBar: config.enableAnnouncementBar !== false,
    showHeroSection: config.showHeroSection !== undefined ? config.showHeroSection : true,
    showSchemeBanner: config.showSchemeBanner !== undefined ? config.showSchemeBanner : true,
    showReviewsSection: config.showReviewsSection !== undefined ? config.showReviewsSection : true,
    showElectronicsSection: config.showElectronicsSection !== undefined ? config.showElectronicsSection : true,
    showFurnitureSection: config.showFurnitureSection !== undefined ? config.showFurnitureSection : true,
    showAddressBanner: config.showAddressBanner !== undefined ? config.showAddressBanner : true,
    showPassbookSection: config.showPassbookSection !== undefined ? config.showPassbookSection : true,
  };
}
