import { LandingPageConfig, LandingHeroSlide, LandingOffer, StockItem } from '../types';

export const DEFAULT_HERO_SLIDES: LandingHeroSlide[] = [
  {
    id: 'slide-1',
    tag: 'SHRI SAI ELECTRONICS EXPO • MEGA FESTIVAL SALE',
    titleLead: 'Smart 4K UHD TVs &',
    titleHighlight: 'Royal Teak Sofas',
    subtitle: 'वर्ध्यातील सर्वात मोठे इलेक्ट्रॉनिक्स व फर्निचर दालन. अस्सल सोनी, सॅमसंग, एलजी 4K स्मार्ट टीव्ही आणि हँडमेड सागवान फर्निचर थेट फॅक्टरी दरात उपलब्ध.',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=1600&auto=format&fit=crop&q=80',
    primaryBtnText: 'होलसेल टीव्ही व फर्निचर कॅटलॉग',
    primaryBtnTarget: 'catalog',
    secondaryBtnText: '३०-महिने बचत योजना पासबुक',
    secondaryBtnTarget: 'passbook',
    cardBadge: 'वर्धा फेस्टिव्हल धमाका',
    cardMetric: '100% Brand Warranty',
    cardMetric2: '०% व्याज सुलभ EMI उपलब्ध',
    themeColor: 'amber',
    active: true,
  },
  {
    id: 'slide-2',
    tag: '30-MONTH SAVINGS SCHEME • दर आठवड्याला ₹100 / ₹200',
    titleLead: 'मासिक लकी ड्रॉ व हमखास',
    titleHighlight: 'फर्निचर व इलेक्ट्रॉनिक्स भेट',
    subtitle: 'दर आठवड्याला फक्त ₹१०० किंवा ₹२०० बचत करा! दरमहा पारदर्शक लकी सोडत — जर तुमचा नंबर ड्रॉ मध्ये लागला, तर सर्व पुढील हप्ते मोफत आणि वस्तू लगेच घरी!',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1600&auto=format&fit=crop&q=80',
    primaryBtnText: 'योजना पासबुक शोधा',
    primaryBtnTarget: 'passbook',
    secondaryBtnText: 'WhatsApp वर कार्ड उघडा',
    secondaryBtnTarget: 'whatsapp',
    cardBadge: 'सर्वात लोकप्रिय योजना',
    cardMetric: 'दर आठवड्याला फक्त ₹१००',
    cardMetric2: 'दरमहा लकी सोडत बक्षीस',
    themeColor: 'purple',
    active: true,
  },
  {
    id: 'slide-3',
    tag: 'PURE TEAKWOOD CRAFTSMANSHIP • थेट फॅक्टरी दर',
    titleLead: 'सागवान सोफा सेट, दिवाण &',
    titleHighlight: 'हेव्ही स्टील कपाट',
    subtitle: 'मध्यस्थांशिवाय थेट फॅक्टरी दरात १००% शुद्ध चंद्रपूर सागवान लाकडापासून बनवलेले टिकाऊ फर्निचर. लाईफटाईम लाकूड गॅरंटी आणि मोफत होम डिलिव्हरी वर्ध्यात.',
    imageUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef0?w=1600&auto=format&fit=crop&q=80',
    primaryBtnText: 'फर्निचर कलेक्शन पहा',
    primaryBtnTarget: 'catalog',
    secondaryBtnText: 'थेट संपर्क साधा',
    secondaryBtnTarget: 'whatsapp',
    cardBadge: 'फॅक्टरी डायरेक्ट रेट',
    cardMetric: 'Direct Factory Wholesale',
    cardMetric2: 'Lifetime Wood Guarantee',
    themeColor: 'emerald',
    active: true,
  },
];

export const DEFAULT_OFFERS: LandingOffer[] = [
  {
    id: 'off-1',
    title: 'स्मार्ट 4K टीव्हीवर ५०% पर्यंत थेट सूट',
    subtitle: 'Samsung, Sony, LG 32" ते 65" स्मार्ट टीव्हीवर बंपर डिस्काउंट + मोफत वॉल माउंटिंग फिटिंग.',
    badge: 'MEGA DEAL',
    discount: '५०% पर्यंत सूट',
    couponCode: 'SAI4KTV',
    validTill: 'या आठवड्यापुरती मर्यादित',
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&auto=format&fit=crop&q=80',
    whatsappMessage: 'नमस्कार, मला स्मार्ट 4K टीव्हीवरील ५०% डिस्काउंट ऑफरबद्दल माहिती हवी आहे.',
    active: true,
  },
  {
    id: 'off-2',
    title: 'सागवान सोफा सेट खरेदीवर सेंटर टेबल मोफत',
    subtitle: 'कोणत्याही 3+1+1 किंवा 3+2 रॉयल सागवान सोफा सेटवर ₹४,५०० चे ग्लास टॉप सेंटर टेबल मोफत!',
    badge: 'मोफत भेट (FREE)',
    discount: '₹४,५०० चे टेबल मोफत',
    couponCode: 'FREETABLE',
    validTill: '३१ तारखेपर्यंत',
    category: 'Furniture',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80',
    whatsappMessage: 'नमस्कार, मला सागवान सोफा सेट व मोफत सेंटर टेबल ऑफरबद्दल विचारायचे आहे.',
    active: true,
  },
  {
    id: 'off-3',
    title: '३०-महिने साप्ताहिक योजना - नवीन कार्डवर ₹५०० रोख सवलत',
    subtitle: 'पहिल्या हप्त्यासोबत मोफत डिजिटल पासबुक, लकी कूपन आणि ₹५०० चे पुढील खरेदी व्हाउचर.',
    badge: 'लकी ड्रॉ ऑफर',
    discount: '₹५०० खरेदी व्हाउचर',
    couponCode: 'LUCKY30',
    validTill: 'नवीन सदस्यांसाठी',
    category: 'Scheme',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop&q=80',
    whatsappMessage: 'नमस्कार, मला ३०-महिने साप्ताहिक बचत योजनेचे नवीन कार्ड काढायचे आहे.',
    active: true,
  },
  {
    id: 'off-4',
    title: 'जुने आणा, नवीन न्या - महा एक्सचेंज ऑफर',
    subtitle: 'जुना टीव्ही, फ्रिज, कुलर किंवा जुना सोफा देऊन नवीन वस्तूवर ₹८,००० पर्यंत अतिरिक्त एक्सचेंज व्हॅल्यू.',
    badge: 'EXCHANGE BONUS',
    discount: '₹८,००० पर्यंत व्हॅल्यू',
    couponCode: 'EXCHANGE2026',
    validTill: 'चालू महिना',
    category: 'Appliances',
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
    whatsappMessage: 'नमस्कार, मला जुने इलेक्ट्रॉनिक्स / फर्निचर एक्सचेंज ऑफरबद्दल माहिती हवी आहे.',
    active: true,
  },
];

export const DEFAULT_LANDING_CONFIG: LandingPageConfig = {
  announcement: {
    enabled: true,
    badge: '🌟 उत्सव विशेष ऑफर',
    text: 'श्री साई एंटरप्रायझेस - वर्धा | भव्य दसरा-दिवाळी महासेल सुरू आहे! सर्व उत्पादनांवर ०% व्याज EMI आणि मोफत होम डिलिव्हरी!',
    highlightText: 'सविस्तर चौकशीसाठी थेट संपर्क साधा',
    whatsappButtonText: 'WhatsApp चौकशी',
  },
  heroSlides: DEFAULT_HERO_SLIDES,
  offers: DEFAULT_OFFERS,
  contactInfo: {
    helpline1: '8766486915',
    helpline2: '8600122978',
    helpline3: '9175537365',
    whatsappNumber: '918766486915',
    addressHindi: 'दुकान क्र. १ व २, मुख्य बाजारपेठ, छत्रपती शिवाजी महाराज चौक जवळ, वर्धा - ४४२००१',
    landmark: 'शिवाजी महाराज चौक, मुख्य रस्ता',
    googleMapLink: 'https://maps.google.com/?q=Wardha+Maharashtra',
    timings: 'सकाळी १०:०० ते रात्री ९:०० (आठवड्याचे सर्व दिवस सुरू)',
  },
  schemeBanner: {
    title: 'वर्ध्यात सर्वात सोप्या हप्त्यांवर आणि ३० महिन्यांच्या बचत योजनेवर फर्निचर व इलेक्ट्रॉनिक्स खरेदी करा!',
    subtitle: 'दर आठवड्याला फक्त ₹१०० किंवा ₹२०० बचत करा! दरमहा पारदर्शक लकी सोडत — जर तुमचा नंबर ड्रॉ मध्ये लागला, तर सर्व पुढील हप्ते १००% मोफत आणि वस्तू लगेच घरी! ३० महिन्यांनी ड्रॉ न लागल्यास पूर्ण जमा रकमेचे फर्निचर किंवा इलेक्ट्रॉनिक्स हमखास उपलब्ध. कोणताही तोटा नाही!',
    badge: '३०-महिने साप्ताहिक बचत व मासिक लकी ड्रॉ योजना • WARDHA\'S #1 SAVINGS SCHEME',
    weeklyBadge1: 'हप्ता फक्त ₹१०० किंवा ₹२०० / आठवडा',
    weeklyBadge2: 'दरमहा लकी ड्रॉ बंपर बक्षीस',
    highlightNote: '१००% सुरक्षित खरेदी हमी',
  },
  enableOffersSection: true,
  enableAnnouncementBar: true,
  showHeroSection: true,
  showSchemeBanner: true,
  showReviewsSection: true,
  showElectronicsSection: false,
  showFurnitureSection: false,
  showAddressBanner: false,
  showPassbookSection: true,
};

export const SAMPLE_SHOWROOM_PRODUCTS: Omit<StockItem, 'id' | 'updatedAt'>[] = [
  {
    code: 'TV-SAM-55-UHD',
    name: 'Samsung 55-inch Crystal 4K UHD Smart TV (AUE60A)',
    category: 'Electronics',
    brand: 'Samsung',
    model: 'UA55AUE60AKXXL',
    purchasePrice: 38000,
    salePrice: 44990,
    mrp: 64900,
    stockQty: 8,
    minAlertQty: 2,
    unit: 'Units',
    warrantyMonths: 24,
    description: '4K Ultra HD Display with PurColor, HDR10+, Smart Hub, 20W Dolby Audio, and AirPlay 2.',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: 'दिवाळी विशेष ३१% सूट',
    schemeWeeklyAmount: 200,
    hideOnLanding: false,
  },
  {
    code: 'TV-LG-43-SMART',
    name: 'LG 43-inch 4K WebOS Smart LED Television',
    category: 'Electronics',
    brand: 'LG',
    model: '43UQ7500PSF',
    purchasePrice: 24500,
    salePrice: 28990,
    mrp: 41990,
    stockQty: 12,
    minAlertQty: 3,
    unit: 'Units',
    warrantyMonths: 24,
    description: 'α5 Gen5 AI Processor 4K, ThinQ AI, Magic Remote Support, and 4K Active HDR.',
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: 'बेस्ट सेलर',
    schemeWeeklyAmount: 150,
    hideOnLanding: false,
  },
  {
    code: 'FURN-SOFA-TEAK-311',
    name: 'Royal Pure Teakwood (सागवान) 3+1+1 Sofa Set with Cushions',
    category: 'Furniture',
    brand: 'Sai Craft',
    model: 'SC-SOFA-ROYAL-TK',
    purchasePrice: 28000,
    salePrice: 35900,
    mrp: 48000,
    stockQty: 5,
    minAlertQty: 1,
    unit: 'Sets',
    warrantyMonths: 60,
    description: '100% Genuine seasoned Chandrapur teakwood frame, 32-density high-resilience foam, with washable velvet fabric.',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: 'फॅक्टरी डायरेक्ट रेट',
    schemeWeeklyAmount: 200,
    hideOnLanding: false,
  },
  {
    code: 'FURN-DIWAN-STORAGE-4X6',
    name: 'Wooden Box Storage Diwan Cot (4x6 Feet) with Hydraulic Lift',
    category: 'Furniture',
    brand: 'Sai Craft',
    model: 'SC-DIWAN-BOX-46',
    purchasePrice: 11000,
    salePrice: 14500,
    mrp: 19500,
    stockQty: 7,
    minAlertQty: 2,
    unit: 'Pcs',
    warrantyMonths: 36,
    description: 'Solid heavy commercial ply & teak border structure with spacious hydraulic storage for blankets and mattresses.',
    imageUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef0?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: 'हॉट ऑफर',
    schemeWeeklyAmount: 100,
    hideOnLanding: false,
  },
  {
    code: 'APPL-FRIDGE-LG-240L',
    name: 'LG 240L Smart Inverter Double Door Refrigerator (Shiny Steel)',
    category: 'Home Appliances',
    brand: 'LG',
    model: 'GL-S292RDSX',
    purchasePrice: 22000,
    salePrice: 26490,
    mrp: 34990,
    stockQty: 6,
    minAlertQty: 2,
    unit: 'Units',
    warrantyMonths: 120,
    description: 'Smart Inverter Compressor, Multi Air Flow Cooling, Toughened Glass Shelves, 10-Year Compressor Warranty.',
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: '५ स्टार बचत',
    schemeWeeklyAmount: 150,
    hideOnLanding: false,
  },
  {
    code: 'FURN-ALMIRAH-STEEL-TRIPLE',
    name: 'Heavy Steel 3-Door Wardrobe Almirah with Locker & Mirror',
    category: 'Furniture',
    brand: 'Steel Craft',
    model: 'SC-ALM-STEEL-3D',
    purchasePrice: 12500,
    salePrice: 16500,
    mrp: 22000,
    stockQty: 9,
    minAlertQty: 2,
    unit: 'Units',
    warrantyMonths: 36,
    description: 'Heavy 18-gauge cold-rolled steel, powder-coated finish, ultra-secure locker box, and full-length dressing mirror.',
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: true,
    landingBadge: 'मजबूत स्टील',
    schemeWeeklyAmount: 100,
    hideOnLanding: false,
  },
  {
    code: 'APPL-WASH-WHIRL-75KG',
    name: 'Whirlpool 7.5 Kg 5 Star Fully Automatic Top Load Washing Machine',
    category: 'Home Appliances',
    brand: 'Whirlpool',
    model: 'WHIRL-ROYAL-75',
    purchasePrice: 13500,
    salePrice: 16990,
    mrp: 22500,
    stockQty: 5,
    minAlertQty: 1,
    unit: 'Units',
    warrantyMonths: 24,
    description: '6th Sense Technology, Spiro Wash Action, Express Wash, Zero Pressure Fill, Hard Water Wash Support.',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: false,
    landingBadge: '०% डाउनपेमेंट',
    schemeWeeklyAmount: 100,
    hideOnLanding: false,
  },
  {
    code: 'APPL-COOLER-SYMPHONY-70L',
    name: 'Heavy Duty 70-Litre Desert Air Cooler with Honeycomb Pads',
    category: 'Home Appliances',
    brand: 'Symphony',
    model: 'DESERT-STORM-70',
    purchasePrice: 8200,
    salePrice: 10990,
    mrp: 14990,
    stockQty: 10,
    minAlertQty: 2,
    unit: 'Units',
    warrantyMonths: 12,
    description: 'High air delivery powerful blower, 3-sided dense honeycomb cooling pads, inverter compatible with castor wheels.',
    imageUrl: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&auto=format&fit=crop&q=80',
    isFeaturedOnLanding: false,
    landingBadge: 'उन्हाळा स्पेशल',
    schemeWeeklyAmount: 100,
    hideOnLanding: false,
  },
];

export function getActiveLandingConfig(config?: LandingPageConfig): LandingPageConfig {
  if (!config) {
    return DEFAULT_LANDING_CONFIG;
  }
  return {
    announcement: {
      ...DEFAULT_LANDING_CONFIG.announcement,
      ...(config.announcement || {}),
    },
    heroSlides: config.heroSlides && config.heroSlides.length > 0 ? config.heroSlides : DEFAULT_HERO_SLIDES,
    offers: config.offers && config.offers.length > 0 ? config.offers : DEFAULT_OFFERS,
    contactInfo: {
      ...DEFAULT_LANDING_CONFIG.contactInfo,
      ...(config.contactInfo || {}),
      helpline1: (config.contactInfo?.helpline1 === '9422114247' || !config.contactInfo?.helpline1)
        ? '8766486915'
        : config.contactInfo.helpline1,
    },
    schemeBanner: {
      ...DEFAULT_LANDING_CONFIG.schemeBanner,
      ...(config.schemeBanner || {}),
    },
    enableOffersSection: config.enableOffersSection !== false,
    enableAnnouncementBar: config.enableAnnouncementBar !== false,
    showHeroSection: config.showHeroSection !== undefined ? config.showHeroSection : true,
    showSchemeBanner: config.showSchemeBanner !== undefined ? config.showSchemeBanner : true,
    showReviewsSection: config.showReviewsSection !== undefined ? config.showReviewsSection : true,
    showElectronicsSection: config.showElectronicsSection !== undefined ? config.showElectronicsSection : false,
    showFurnitureSection: config.showFurnitureSection !== undefined ? config.showFurnitureSection : false,
    showAddressBanner: config.showAddressBanner !== undefined ? config.showAddressBanner : false,
    showPassbookSection: config.showPassbookSection !== undefined ? config.showPassbookSection : true,
  };
}
