import { StoreData, Customer, CardMember, Transaction, BillReceipt, StockItem } from './types';

export const cleanDemoCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'VIJAY GADE',
    phone: '9822100001',
    village: 'Waifad (वायफड)',
    city: 'Waifad',
    address: 'Waifad Road, Wardha',
    totalPurchased: 44990,
    currentBalance: 0,
    creditLimit: 25000,
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'cust-2',
    name: 'CHETAN KANGANE',
    phone: '9822100002',
    village: 'Wardha (वर्धा)',
    city: 'Wardha',
    address: 'Main Market, Wardha',
    totalPurchased: 32990,
    currentBalance: 0,
    creditLimit: 30000,
    createdAt: '2026-09-02T11:00:00Z',
  },
  {
    id: 'cust-3',
    name: 'YOGESH THAKARE',
    phone: '9822100003',
    village: 'Satoda (साटोडा)',
    city: 'Satoda',
    address: 'Station Road, Satoda',
    totalPurchased: 26490,
    currentBalance: 5000,
    creditLimit: 20000,
    createdAt: '2026-09-03T12:00:00Z',
  },
  {
    id: 'cust-4',
    name: 'SAPNA NAGRALE',
    phone: '9822100004',
    village: 'Wardha (वर्धा)',
    city: 'Wardha',
    address: 'Shivaji Chowk, Wardha',
    totalPurchased: 18990,
    currentBalance: 3200,
    creditLimit: 15000,
    createdAt: '2026-09-04T14:00:00Z',
  },
  {
    id: 'cust-5',
    name: 'SANJAY DHONGADE',
    phone: '9822100005',
    village: 'Seloo (सेलू)',
    city: 'Seloo',
    address: 'Bus Stand Chowk, Seloo',
    totalPurchased: 34500,
    currentBalance: 0,
    creditLimit: 35000,
    createdAt: '2026-09-05T15:00:00Z',
  },
  {
    id: 'cust-6',
    name: 'RAMESHWAR PAWAR',
    phone: '9822100006',
    village: 'Wardha (वर्धा)',
    city: 'Wardha',
    address: 'Punjab Colony, Wardha',
    totalPurchased: 41900,
    currentBalance: 0,
    creditLimit: 50000,
    createdAt: '2026-09-06T16:00:00Z',
  },
];

export const cleanDemoCards: CardMember[] = [
  // Scheme 1 (Card range 1001-3000)
  {
    id: 'cm-1',
    cardNo: 'SCH1-1001',
    schemeNo: 1,
    schemeName: 'योजना १ (Scheme 1)',
    memberName: 'RAMESHWAR PAWAR',
    phone: '9822100006',
    village: 'Wardha (वर्धा)',
    address: 'Punjab Colony, Wardha',
    nomineeName: 'Sunita Pawar (Wife)',
    startDate: '2024-04-10',
    endDate: '2026-10-10',
    totalPaidMonths: 28,
    totalAmountPaid: 28000,
    monthlyAmount: 1000,
    durationMonths: 30,
    status: 'Active',
    collectedBy: 'Bhushan Lidbe',
  },
  {
    id: 'cm-2',
    cardNo: 'SCH1-1002',
    schemeNo: 1,
    schemeName: 'योजना १ (Scheme 1)',
    memberName: 'PRAVIN RAUT',
    phone: '9822100007',
    village: 'Sevagram (सेवाग्राम)',
    address: 'Near Ashram, Sevagram',
    nomineeName: 'Kavita Raut',
    startDate: '2024-02-15',
    endDate: '2026-08-15',
    totalPaidMonths: 30,
    totalAmountPaid: 30000,
    monthlyAmount: 1000,
    durationMonths: 30,
    status: 'Matured',
    collectedBy: 'Shubham Shende',
  },
  {
    id: 'cm-3',
    cardNo: 'SCH1-1050',
    schemeNo: 1,
    schemeName: 'योजना १ (Scheme 1)',
    memberName: 'KAILASH SHINDE',
    phone: '9822100008',
    village: 'Waifad (वायफड)',
    address: 'Main Road, Waifad',
    nomineeName: 'Rahul Shinde (Son)',
    startDate: '2025-05-10',
    endDate: '2027-11-10',
    totalPaidMonths: 15,
    totalAmountPaid: 15000,
    monthlyAmount: 1000,
    durationMonths: 30,
    status: 'Active',
    collectedBy: 'Bhushan Lidbe',
  },
  // Scheme 2 (Card range 1001-3000)
  {
    id: 'cm-4',
    cardNo: 'SCH2-1001',
    schemeNo: 2,
    schemeName: 'योजना २ (Scheme 2)',
    memberName: 'GANESH SHRIKANT BHENDE',
    phone: '9822100009',
    village: 'Seloo (सेलू)',
    address: 'Old Wardha Road, Seloo',
    nomineeName: 'Shrikant Bhende',
    startDate: '2024-11-01',
    endDate: '2027-05-01',
    totalPaidMonths: 20,
    totalAmountPaid: 20000,
    monthlyAmount: 1000,
    durationMonths: 30,
    status: 'Draw Winner',
    prizeDetails: 'Samsung 43" Smart LED TV (Month #18 Draw Winner)',
    collectedBy: 'Rahul Wankhede',
  },
  {
    id: 'cm-5',
    cardNo: 'SCH2-1088',
    schemeNo: 2,
    schemeName: 'योजना २ (Scheme 2)',
    memberName: 'PRAMILA GAJANANRAO DESHMUKH',
    phone: '9822100010',
    village: 'Wardha (वर्धा)',
    address: 'Kelkar Wadi, Wardha',
    nomineeName: 'Gajananrao Deshmukh',
    startDate: '2025-06-01',
    endDate: '2027-12-01',
    totalPaidMonths: 14,
    totalAmountPaid: 14000,
    monthlyAmount: 1000,
    durationMonths: 30,
    status: 'Active',
    collectedBy: 'Sachin Deshmukh',
  },
  // Scheme 3 (Card range 1001-6000)
  {
    id: 'cm-6',
    cardNo: 'SCH3-1001',
    schemeNo: 3,
    schemeName: 'योजना ३ (Scheme 3)',
    memberName: 'DR. VIVEK S. KULKARNI',
    phone: '9822100011',
    village: 'Wardha (वर्धा)',
    address: 'Civil Lines, Wardha',
    nomineeName: 'Dr. Anagha Kulkarni',
    startDate: '2025-02-15',
    endDate: '2027-08-15',
    totalPaidMonths: 18,
    totalAmountPaid: 18000,
    monthlyAmount: 1000,
    durationMonths: 30,
    status: 'Active',
    collectedBy: 'Suraj Moon',
  },
  {
    id: 'cm-7',
    cardNo: 'SCH3-2500',
    schemeNo: 3,
    schemeName: 'योजना ३ (Scheme 3)',
    memberName: 'VINODRAO THAKARE',
    phone: '9822100012',
    village: 'Deoli (देवळी)',
    address: 'Bazaar Chowk, Deoli',
    nomineeName: 'Sunil Thakare',
    startDate: '2026-02-01',
    endDate: '2028-08-01',
    totalPaidMonths: 7,
    totalAmountPaid: 7000,
    monthlyAmount: 1000,
    durationMonths: 30,
    status: 'Active',
    collectedBy: 'Suraj Moon',
  },
  {
    id: 'cm-8',
    cardNo: 'SCH3-5500',
    schemeNo: 3,
    schemeName: 'योजना ३ (Scheme 3)',
    memberName: 'ANANDRAO WANKHEDE',
    phone: '9822100013',
    village: 'Hinganghat (हिंगणघाट)',
    address: 'Station Road, Hinganghat',
    nomineeName: 'Vikas Wankhede',
    startDate: '2025-10-10',
    endDate: '2028-04-10',
    totalPaidMonths: 11,
    totalAmountPaid: 11000,
    monthlyAmount: 1000,
    durationMonths: 30,
    status: 'Active',
    collectedBy: 'Bhushan Lidbe',
  },
];

export const cleanDemoTransactions: Transaction[] = [
  {
    id: 'tx-1',
    invoiceNo: 'SSE-INV-1001',
    date: '2026-09-10T11:00:00Z',
    customerId: 'cust-1',
    customerName: 'VIJAY GADE',
    customerPhone: '9822100001',
    items: [
      {
        stockId: 'stk-1',
        name: 'Samsung 55-inch Crystal 4K UHD Smart TV',
        brand: 'Samsung',
        qty: 1,
        rate: 44990,
        discountPct: 0,
        taxPct: 0,
        total: 44990,
      }
    ],
    subtotal: 44990,
    discountTotal: 0,
    taxTotal: 0,
    grandTotal: 44990,
    paidAmount: 44990,
    balanceDue: 0,
    paymentMode: 'UPI',
    status: 'Paid',
    deliveryStatus: 'Delivered',
    createdBy: 'Rahul Joshi',
    remarks: 'Paid via PhonePe at counter.',
  },
  {
    id: 'tx-2',
    invoiceNo: 'SSE-INV-1002',
    date: '2026-09-12T14:30:00Z',
    customerId: 'cust-3',
    customerName: 'YOGESH THAKARE',
    customerPhone: '9822100003',
    items: [
      {
        stockId: 'stk-2',
        name: 'LG 242L Smart Inverter Double Door Refrigerator',
        brand: 'LG',
        qty: 1,
        rate: 26490,
        discountPct: 0,
        taxPct: 0,
        total: 26490,
      }
    ],
    subtotal: 26490,
    discountTotal: 0,
    taxTotal: 0,
    grandTotal: 26490,
    paidAmount: 21490,
    balanceDue: 5000,
    paymentMode: 'Cash',
    status: 'Partial',
    deliveryStatus: 'Delivered',
    createdBy: 'Rahul Joshi',
    remarks: 'Down payment ₹21,490 cash. Balance ₹5,000 on Khata.',
  },
  {
    id: 'tx-3',
    invoiceNo: 'SSE-INV-1003',
    date: '2026-09-14T16:00:00Z',
    customerId: 'cust-4',
    customerName: 'SAPNA NAGRALE',
    customerPhone: '9822100004',
    items: [
      {
        stockId: 'stk-7',
        name: 'Whirlpool 7.5 kg 5 Star Fully Automatic Washing Machine',
        brand: 'Whirlpool',
        qty: 1,
        rate: 18990,
        discountPct: 0,
        taxPct: 0,
        total: 18990,
      }
    ],
    subtotal: 18990,
    discountTotal: 0,
    taxTotal: 0,
    grandTotal: 18990,
    paidAmount: 15790,
    balanceDue: 3200,
    paymentMode: 'UPI',
    status: 'Partial',
    deliveryStatus: 'Delivered',
    createdBy: 'Rahul Joshi',
    remarks: 'GPay ₹15,790. Remaining ₹3,200 due next week.',
  },
  {
    id: 'tx-4',
    invoiceNo: 'SSE-INV-1004',
    date: '2026-09-15T12:15:00Z',
    customerId: 'cust-2',
    customerName: 'CHETAN KANGANE',
    customerPhone: '9822100002',
    items: [
      {
        stockId: 'stk-3',
        name: 'Voltas 1.5 Ton 3 Star Inverter Split AC',
        brand: 'Voltas',
        qty: 1,
        rate: 32990,
        discountPct: 0,
        taxPct: 0,
        total: 32990,
      }
    ],
    subtotal: 32990,
    discountTotal: 0,
    taxTotal: 0,
    grandTotal: 32990,
    paidAmount: 32990,
    balanceDue: 0,
    paymentMode: 'Card',
    status: 'Paid',
    deliveryStatus: 'Delivered',
    createdBy: 'Rahul Joshi',
    remarks: 'Paid full by HDFC Debit Card swipe.',
  },
];

export const cleanDemoBillReceipts: BillReceipt[] = [
  {
    id: 'rec-1',
    receiptNo: 1084,
    date: '2026-09-11T11:30:00Z',
    customerId: 'cust-1',
    customerName: 'VIJAY GADE',
    amountPaid: 1700,
    paymentMode: 'UPI',
    balanceRemaining: 0,
    handledBy: 'Bhushan Lidbe',
    remarks: 'Previous Khata balance settled via PhonePe.',
  },
  {
    id: 'rec-2',
    receiptNo: 1085,
    date: '2026-09-13T15:00:00Z',
    customerId: 'cust-2',
    customerName: 'CHETAN KANGANE',
    amountPaid: 14000,
    paymentMode: 'Cash',
    balanceRemaining: 0,
    handledBy: 'Shubham Shende',
    remarks: 'Counter cash payment for Khata clearance.',
  },
  {
    id: 'rec-3',
    receiptNo: 1086,
    date: '2026-09-16T17:20:00Z',
    customerId: 'cust-3',
    customerName: 'YOGESH THAKARE',
    amountPaid: 5000,
    paymentMode: 'Cash',
    balanceRemaining: 5000,
    handledBy: 'Bhushan Lidbe',
    remarks: 'Satoda village collection cash receipt.',
  },
];

export const cleanDemoStock: StockItem[] = [
  {
    id: 'stk-1',
    code: 'ELE-SAM-55Q',
    name: 'Samsung 55-inch Crystal 4K UHD Smart TV',
    category: 'Electronics',
    brand: 'Samsung',
    model: 'UA55DUE70AKXXL',
    serialNo: 'SAM202655Q0981',
    purchasePrice: 37500,
    salePrice: 44990,
    mrp: 52900,
    stockQty: 8,
    minAlertQty: 2,
    unit: 'Pcs',
    location: 'Floor 1 - Section A',
    warrantyMonths: 24,
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
    description: 'Crystal Processor 4K, HDR 10+, OTS Lite Sound, Multi Voice Assistant & 2-Yr Warranty',
    updatedAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'stk-2',
    code: 'ELE-LG-242L',
    name: 'LG 242L Smart Inverter Double Door Refrigerator',
    category: 'Home Appliances',
    brand: 'LG',
    model: 'GL-I292RPZX',
    serialNo: 'LG242LREF8829',
    purchasePrice: 22800,
    salePrice: 26490,
    mrp: 31990,
    stockQty: 12,
    minAlertQty: 3,
    unit: 'Pcs',
    location: 'Floor 1 - Section B',
    warrantyMonths: 12,
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80',
    description: 'Smart Inverter Compressor, Multi Air Flow Cooling, Anti-Bacterial Gasket & Toughened Glass',
    updatedAt: '2026-09-11T11:00:00Z',
  },
  {
    id: 'stk-3',
    code: 'ELE-VOL-1.5T',
    name: 'Voltas 1.5 Ton 3 Star Inverter Split AC',
    category: 'Home Appliances',
    brand: 'Voltas',
    model: '183V Vectra Prism',
    serialNo: 'VOLAC15T7711',
    purchasePrice: 27400,
    salePrice: 32990,
    mrp: 38990,
    stockQty: 3,
    minAlertQty: 4,
    unit: 'Pcs',
    location: 'Floor 1 - AC Display',
    warrantyMonths: 12,
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80',
    description: '100% Copper Condenser, 4-in-1 Adjustable Mode, Anti-Dust Filter & Turbo Cooling at 52°C',
    updatedAt: '2026-09-12T14:30:00Z',
  },
  {
    id: 'stk-4',
    code: 'FUR-BED-KG',
    name: 'Royal Solid Sheesham Wood King Size Bed with Hydraulic Storage',
    category: 'Furniture',
    brand: 'Sai Artisan',
    model: 'SSE-ROYAL-KING',
    purchasePrice: 26000,
    salePrice: 34500,
    mrp: 42000,
    stockQty: 5,
    minAlertQty: 2,
    unit: 'Sets',
    location: 'Floor 2 - Furniture Gallery',
    warrantyMonths: 60,
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&auto=format&fit=crop&q=80',
    description: 'अस्सल सागवान व शीशम लाकूड, मजबूत हायड्रोलिक स्टोरेज बॉक्स, ५ वर्षे वॉरंटी',
    updatedAt: '2026-09-14T09:00:00Z',
  },
  {
    id: 'stk-5',
    code: 'FUR-SOF-32',
    name: 'Modern Luxury 3+2 Teakwood Fabric Recliner Sofa Set',
    category: 'Furniture',
    brand: 'Sai Artisan',
    model: 'SSE-RECLINE-32',
    purchasePrice: 31000,
    salePrice: 41900,
    mrp: 49900,
    stockQty: 4,
    minAlertQty: 2,
    unit: 'Sets',
    location: 'Floor 2 - Living Room Suite',
    warrantyMonths: 36,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop&q=80',
    description: '३+२ रॉयल सोफा सेट, अस्सल सागवान फ्रेम, हाय-डेन्सिटी फोम, प्रीमियम वेल्वेट फॅब्रिक',
    updatedAt: '2026-09-15T15:00:00Z',
  },
  {
    id: 'stk-6',
    code: 'FUR-DIN-6S',
    name: '6-Seater Italian White Marble Top Dining Table with Chairs',
    category: 'Furniture',
    brand: 'Sai Artisan',
    model: 'SSE-DINING-MARBLE',
    purchasePrice: 28500,
    salePrice: 37900,
    mrp: 45000,
    stockQty: 2,
    minAlertQty: 2,
    unit: 'Sets',
    location: 'Floor 2 - Dining Hub',
    warrantyMonths: 24,
    imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&auto=format&fit=crop&q=80',
    description: 'प्रीमियम इटालियन मार्बल टॉप, ६ आरामदायी लेदर कुशन खुर्च्या, सागवान पाय',
    updatedAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'stk-7',
    code: 'APP-WASH-WHI',
    name: 'Whirlpool 7.5 kg 5 Star Fully Automatic Top Load Washing Machine',
    category: 'Home Appliances',
    brand: 'Whirlpool',
    model: '360 Bloomwash Pro',
    serialNo: 'WPL75KG6632',
    purchasePrice: 15800,
    salePrice: 18990,
    mrp: 23500,
    stockQty: 7,
    minAlertQty: 2,
    unit: 'Pcs',
    location: 'Floor 1 - Appliances',
    warrantyMonths: 24,
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80',
    description: '5 Star Energy Rating, Hard Water Wash, Zero Pressure Fill Technology & 10-Yr Motor Warranty',
    updatedAt: '2026-09-16T16:00:00Z',
  },
  {
    id: 'stk-8',
    code: 'APP-MIC-PAN',
    name: 'Panasonic 27L Convection Microwave Oven with Auto Cook',
    category: 'Kitchen Appliances',
    brand: 'Panasonic',
    model: 'NN-CT645BFDG',
    serialNo: 'PANMIC27L991',
    purchasePrice: 10200,
    salePrice: 12490,
    mrp: 14990,
    stockQty: 6,
    minAlertQty: 2,
    unit: 'Pcs',
    location: 'Floor 1 - Counter Display',
    warrantyMonths: 12,
    imageUrl: 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=800&auto=format&fit=crop&q=80',
    description: '101 Auto Cook Menus, 360° Heat Distribution, Stainless Steel Cavity & Glass Turntable',
    updatedAt: '2026-09-17T11:00:00Z',
  },
  {
    id: 'stk-9',
    code: 'FUR-DIW-TEAK',
    name: 'Authentic Teakwood Diwan Bed with Heavy Storage Box (4x6 Ft)',
    category: 'Furniture',
    brand: 'Sai Artisan',
    model: 'SSE-DIWAN-4X6',
    purchasePrice: 16500,
    salePrice: 21500,
    mrp: 26000,
    stockQty: 4,
    minAlertQty: 1,
    unit: 'Sets',
    location: 'Floor 2 - Diwan Gallery',
    warrantyMonths: 36,
    imageUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef0?w=800&auto=format&fit=crop&q=80',
    description: 'अस्सल सागवान लाकडी दिवाण कॉट, ४x६ साईझ, बॉक्स स्टोरेज, मजबूत लाकूड पॉलिश',
    updatedAt: '2026-09-18T10:00:00Z',
  },
  {
    id: 'stk-10',
    code: 'FUR-ALM-STL',
    name: 'Godrej Type Heavy Duty Steel Almirah 3-Door with Full Mirror',
    category: 'Furniture',
    brand: 'Sai Steel',
    model: 'SSE-STEEL-3D',
    purchasePrice: 13500,
    salePrice: 17500,
    mrp: 21000,
    stockQty: 5,
    minAlertQty: 2,
    unit: 'Pcs',
    location: 'Floor 2 - Cupboards',
    warrantyMonths: 60,
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&auto=format&fit=crop&q=80',
    description: '२० गेज हेवी CRCA स्टील, प्रायव्हेट लॉकर, फुल ड्रेसिंग काच आणि ५ लेव्हल पावडर कोटिंग',
    updatedAt: '2026-09-18T14:00:00Z',
  },
  {
    id: 'stk-11',
    code: 'APP-CLR-DES',
    name: 'Symphony Heavy Desert Air Cooler 75L Honeycomb (Metal/Fibre)',
    category: 'Home Appliances',
    brand: 'Symphony',
    model: 'SSE-DESERT-75L',
    purchasePrice: 8200,
    salePrice: 10490,
    mrp: 13500,
    stockQty: 8,
    minAlertQty: 3,
    unit: 'Pcs',
    location: 'Floor 1 - Summer Cooler Hub',
    warrantyMonths: 12,
    imageUrl: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&auto=format&fit=crop&q=80',
    description: '७५ लिटर क्षमता, हेवी ३-स्पीड कॉपर मोटर, हनीकॉम्ब पॅड्स, ५० फूट एअर थ्रो',
    updatedAt: '2026-09-19T09:00:00Z',
  },
];

export const initialStoreData: StoreData = {
  updatedAt: new Date().toISOString(),
  updatedBy: 'Admin (Clean Slate)',
  settings: {
    storeName: 'SHRI SAI ENTERPRISES',
    businessNameHindi: 'श्री साई इंटरप्राइजेस',
    domainName: 'shrisaient.in',
    ownerName: 'Shubham Shende',
    role: 'Admin',
    tagline: 'Electronics, Home Appliances, Wires & Hardware Trading • 30-Month Card Scheme',
    address: 'Opposite Matoshree Sabhagruh, Arvi Road, Punjab Colony, Wardha, 442001',
    addressHindi: 'मातोश्री सभागृह समोर, आर्वी रोड, पंजाब कॉलनी, वर्धा - ४४२००१',
    city: 'Wardha',
    pincode: '442001',
    state: 'Maharashtra',
    phone: '8600122978',
    additionalPhones: ['9175537365', '8766486915'],
    email: 'shubhamh3098@gmail.com',
    gstin: '27ALOPL0030G2ZC',
    panNumber: 'ALOPL0030G',
    bankDetails: {
      bankName: 'HDFC Bank',
      accountNumber: '50200083215914',
      ifscCode: 'HDFC0000965',
      branch: 'OPP. BANK OF MAHARASHTRA, WARDHA 442001',
      upiId: '8766486915@ybl',
    },
    invoicePrefix: 'INV-2026-',
    nextReceiptNo: 1087, // Next receipt starts clean at #1087
    currencySymbol: '₹',
    deliveryRates: {
      freeDeliveryMinAmount: 3000,
      localDeliveryFee: 100,
      outerDeliveryFee: 250,
      estimatedDeliveryTime: 'Same Day / 24 Hours',
      deliveryAreas: 'Wardha City, Arvi, and All Surrounding Villages (50 km)',
      deliveryNote: 'Free home delivery on orders above ₹3,000 and all Card Scheme major appliances (TV, Refrigerator, Cooler, Washing Machine).',
    },
    shopNotice: 'श्री साई इंटरप्राइजेस: ३०-महिने साप्ताहिक बचत कार्ड योजना बुकिंग चालू आहे • सर्व मोठ्या वस्तूंवर फ्री होम डिलिव्हरी!',
    whatsappGroupLink: 'https://chat.whatsapp.com/invite/shrisaienterprises',
    whatsappOrderNumber: '8766486915',
    whatsappSecondaryNumber: '8600122798',
    warrantyDisclaimer: 'दिलेली वॉरंटी ही दुकानदाराची नसून कंपनीची आहे. म्हणून वस्तूत काही बिघाड आल्यास त्याला दुकानदार जबाबदार नसून कंपनी आहे. तेव्हा कृपया वस्तू घेतेवेळेस कंपनीच्या सर्व्हिस सेण्टरचा मोबाईल नंबर घ्यावा.',
    schemeDefaults: {
      schemeName: 'Shri Sai 30-Month Samruddhi Savings Scheme',
      durationMonths: 30,
      monthlyAmount: 1000,
      totalBenefit: 'Maturity worth ₹33,500 on Electronics/Furniture + Monthly Lucky Draw Eligibility',
    },
    schemesList: [
      {
        id: 'scheme1',
        name: 'Scheme 1 (योजना 1)',
        code: 'SCH-1',
        startCardNo: 1001,
        endCardNo: 2999,
        registrationFee: 50,
        description: '३०-महिने साप्ताहिक बचत योजना 1 • कार्ड नं 1001 ते 2999 • सर्व मोठ्या होम अप्लायंसेजवर लागू',
        color: 'from-blue-600 to-blue-800',
      },
      {
        id: 'scheme2',
        name: 'Scheme 2 (योजना 2)',
        code: 'SCH-2',
        startCardNo: 3001,
        endCardNo: 3999,
        registrationFee: 50,
        description: '३०-महिने साप्ताहिक बचत योजना 2 • कार्ड नं 3001 ते 3999 • कुलर, फ्रिज, वॉशिंग मशीन',
        color: 'from-emerald-600 to-teal-800',
      },
      {
        id: 'scheme3',
        name: 'Scheme 3 (योजना 3)',
        code: 'SCH-3',
        startCardNo: 1001,
        endCardNo: 6000,
        registrationFee: 50,
        description: '३०-महिने साप्ताहिक बचत योजना 3 • कार्ड नं 1001 ते 6000 • स्मार्ट टीव्ही, एलईडी व इलेक्ट्रॉनिक्स',
        color: 'from-purple-600 to-indigo-800',
      },
      {
        id: 'scheme4',
        name: 'Scheme 4 (योजना 4)',
        code: 'SCH-4',
        startCardNo: 6001,
        endCardNo: 7999,
        registrationFee: 50,
        description: 'साप्ताहिक बचत योजना 4 • कार्ड नं 6001 ते 7999 • प्रीमियम इलेक्ट्रॉनिक्स व फर्निचर',
        color: 'from-amber-600 to-orange-800',
      },
      {
        id: 'scheme5',
        name: 'Scheme 5 (योजना 5)',
        code: 'SCH-5',
        startCardNo: 8001,
        endCardNo: 9999,
        registrationFee: 50,
        description: 'साप्ताहिक बचत योजना 5 • कार्ड नं 8001 ते 9999 • नवीन ऑफर्स व फेस्टिव्हल स्कीम',
        color: 'from-pink-600 to-rose-800',
      },
      {
        id: 'scheme6',
        name: 'Scheme 6 (योजना 6)',
        code: 'SCH-6',
        startCardNo: 10001,
        endCardNo: 12000,
        registrationFee: 50,
        description: 'साप्ताहिक बचत योजना 6 • कार्ड नं 10001 ते 12000 • सुपर सेव्हर वीकली स्कीम',
        color: 'from-cyan-600 to-blue-900',
      },
    ],
    termsAndConditions: [
      'Goods once sold cannot be returned without original cash memo and warranty card.',
      'Warranty service is directly handled by respective authorized brand service centers.',
      'Scheme monthly installment must be cleared before the 10th of every calendar month.',
      'Subject to Wardha Jurisdiction only.',
      'दिलेली वॉरंटी ही दुकानदाराची नसून कंपनीची आहे.',
    ],
  },
  stock: [],
  customers: [],
  transactions: [],
  purchases: [],
  dealers: [
    {
      id: 'dlr-1',
      name: 'Samsung Electronics India Ltd (Nagpur Hub)',
      companyName: 'Samsung India Pvt Ltd',
      phone: '+91 712-2554433',
      email: 'sales.nagpur@samsung.com',
      city: 'Nagpur',
      openingBalance: 0,
      currentPayable: 0,
      notes: 'Key distributor for LED TVs and Refrigerators.',
    },
    {
      id: 'dlr-2',
      name: 'Sai Wooden Craft Works (Jodhpur)',
      companyName: 'Sai Wooden Handicrafts',
      phone: '+91 94141 55678',
      email: 'jodhpurwood@crafts.in',
      city: 'Jodhpur',
      openingBalance: 0,
      currentPayable: 0,
      notes: 'Solid Sheesham wood bedroom suites and dining sets.',
    },
    {
      id: 'dlr-3',
      name: 'Voltas Appliances Regional Agency',
      companyName: 'Tata Voltas Commercial Ltd',
      phone: '+91 712-2980112',
      email: 'voltas.eastmaharashtra@voltas.com',
      city: 'Nagpur',
      openingBalance: 0,
      currentPayable: 0,
      notes: 'Air conditioners and commercial deep freezers.',
    }
  ],
  dealerPayments: [],
  cardMembers: [],
  cardTransactions: [],
  staff: [
    {
      id: 'stf-1',
      name: 'Bhushan Lidbe',
      role: 'Agent',
      phone: '+91 87664 86915',
      monthlySalary: 25000,
      joiningDate: '2022-01-01',
      isActive: true,
    },
    {
      id: 'stf-2',
      name: 'Shubham Shende',
      role: 'Agent',
      phone: '+91 86001 22978',
      monthlySalary: 25000,
      joiningDate: '2022-01-01',
      isActive: true,
    },
    {
      id: 'stf-3',
      name: 'Suraj Moon',
      role: 'Agent',
      phone: '+91 91755 34365',
      monthlySalary: 22000,
      joiningDate: '2022-06-01',
      isActive: true,
    },
    {
      id: 'stf-4',
      name: 'Rahul Wankhede',
      role: 'Agent',
      phone: '+91 97664 11220',
      monthlySalary: 18000,
      joiningDate: '2023-02-15',
      isActive: true,
    },
    {
      id: 'stf-5',
      name: 'Sachin Deshmukh',
      role: 'Agent',
      phone: '+91 94220 33441',
      monthlySalary: 18000,
      joiningDate: '2023-04-10',
      isActive: true,
    },
    {
      id: 'stf-6',
      name: 'Pravin Raut',
      role: 'Agent',
      phone: '+91 91580 77889',
      monthlySalary: 16000,
      joiningDate: '2023-09-01',
      isActive: true,
    },
    {
      id: 'stf-7',
      name: 'Aniket Gawande',
      role: 'Sales Executive',
      phone: '+91 97664 33221',
      monthlySalary: 16000,
      joiningDate: '2024-01-10',
      isActive: true,
    },
    {
      id: 'stf-8',
      name: 'Mahesh Sharma',
      role: 'Floor Manager',
      phone: '+91 98221 00991',
      monthlySalary: 28000,
      joiningDate: '2022-04-01',
      isActive: true,
    },
    {
      id: 'stf-9',
      name: 'Rahul Joshi',
      role: 'Cashier',
      phone: '+91 94220 77112',
      monthlySalary: 20000,
      joiningDate: '2023-06-15',
      isActive: true,
    }
  ],
  expenses: [],
  agentAdvances: [],
  billReceipts: [],
  authSessions: [],
  adminUsers: [
    {
      id: 'usr-1',
      username: 'admin',
      displayName: 'Owner / General Manager',
      role: 'Admin',
      pin: '1234',
    },
    {
      id: 'usr-2',
      username: 'cashier',
      displayName: 'Rahul Joshi (Cash Counter)',
      role: 'Cashier',
      pin: '0000',
    },
    {
      id: 'usr-3',
      username: 'manager',
      displayName: 'Mahesh Sharma (Floor Mgr)',
      role: 'Manager',
      pin: '5555',
    }
  ],
  isDemoWiped: true,
};
